spring.application.name=student-management

# Utilisation de variables d'environnement avec valeurs par défaut
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-service:3306/testdb?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8089
server.servlet.context-path=/student